version: '3.3'
services:
  db-postgres13:
    container_name: postgres13
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: 'vladislav'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'my_db'
    ports:
      # <Port exposed> : <PG Port running inside container>
      - '5432:5432'
    expose:
      # Opens PG port on the container to other services
      - '5432'
      # Where our data will be persisted
    volumes:
      - postgres13:/var/lib/postgresql/data
# Names our volume
volumes:
  postgres13: