package com.example.oop.repositories;

import com.example.oop.entities.GoodsEntity;
import com.example.oop.exceptions.HttpException;
import com.example.oop.Properties;

import javax.servlet.http.HttpServletResponse;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;

public class GoodsRepository {
    public GoodsRepository() {
        try {
            Class.forName("org.postgresql.Driver");
        } catch (ClassNotFoundException e) {
            throw new RuntimeException(e);
        }
        try (Connection connection = DriverManager.getConnection(
                Properties.getInstance().getDatabaseUrl(),
                Properties.getInstance().getDatabaseUsername(),
                Properties.getInstance().getDatabasePassword());
             Statement statement = connection.createStatement()) {
            statement.execute("""
                    create table if not exists goods
                    (
                        id    int8 generated by default as identity,
                        count int8,
                        name  varchar(255),
                        price int8,
                        primary key (id)
                    );
                    """);
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    public List<GoodsEntity> findAll() {
        try (Connection connection = DriverManager.getConnection(
                Properties.getInstance().getDatabaseUrl(),
                Properties.getInstance().getDatabaseUsername(),
                Properties.getInstance().getDatabasePassword());
             Statement statement = connection.createStatement()) {
            ResultSet resultSet = statement.executeQuery("SELECT * FROM goods ORDER BY id;");
            ArrayList<GoodsEntity> result = new ArrayList<>();
            while (resultSet.next()) {
                result.add(GoodsEntity.builder()
                        .id(resultSet.getLong("id"))
                        .name(resultSet.getString("name"))
                        .price(resultSet.getLong("price"))
                        .count(resultSet.getLong("count"))
                        .build());
            }
            return result;
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    public GoodsEntity findById(Long id) {
        try (Connection connection = DriverManager.getConnection(
                Properties.getInstance().getDatabaseUrl(),
                Properties.getInstance().getDatabaseUsername(),
                Properties.getInstance().getDatabasePassword());
             Statement statement = connection.createStatement()) {
            ResultSet resultSet = statement.executeQuery("SELECT * FROM goods WHERE id = '%s';".formatted(id));
            if (!resultSet.next()) {
                throw new HttpException(HttpServletResponse.SC_NOT_FOUND);
            }
            return GoodsEntity.builder()
                    .id(resultSet.getLong("id"))
                    .name(resultSet.getString("name"))
                    .price(resultSet.getLong("price"))
                    .count(resultSet.getLong("count"))
                    .build();
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    public void updateCount(Long id, Long nuwCount) {
        try (Connection connection = DriverManager.getConnection(
                Properties.getInstance().getDatabaseUrl(),
                Properties.getInstance().getDatabaseUsername(),
                Properties.getInstance().getDatabasePassword());
             Statement statement = connection.createStatement()) {
            statement.execute("UPDATE goods SET count = %s WHERE id = %s;"
                    .formatted(nuwCount, id));
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }
}
